% Hechos
hombre(homer)
adulto(homer)
vive(homer, casa_springfield)
trabaja(homer, responsable_central)
gusta(homer, carne)
come(homer, churrasco)
come(homer, criollo)
come(homer, chorizo)
gusta(homer, beber_bar_moe)

mujer(marge)
adulto(marge)
pareja(homer, marge)
pareja(marge, homer)
vive(marge, casa_springfield)
trabaja(marge, ama_casa)
gusta(marge, carne)
come(marge, churrasco)
come(marge, criollo)
come(marge, chorizo)
aficcion(marge, leer)

niño(bart)
hijo(bart, homer)
hijo(bart, marge)
padre(homer, bart)
madre(marge, bart)
vive(bart, casa_springfield)
estudia(bart, colegio_primaria)
come(bart, churrasco)
come(bart, criollo)
not(come(bart, chorizo))  % mirar si hacer hecho: not_come
gusta(bart, skate)

niño(lisa)
mujer(lisa)
hijo(lisa, homer)
hijo(lisa, marge)
padre(homer, lisa)
madre(marge, lisa)
vive(lisa, casa_springfield)
estudia(lisa, colegio_primaria)
not(gusta(lisa, carne))
es(lisa, vegetariana)
gusta(lisa, jugar_muñecas_stacymalibu)

hijo(maggie, homer)
hijo(maggie, marge)
padre(homer, maggie)
madre(marge, maggie)
vive(maggie, casa_springfield)
not(estudia(maggie, _))
not(gusta(maggie, carne))
not(gusta(maggie, vegetales))
gusta(maggie, chupete)

adulto(abbe).
padre(abbe, homer).
vive(abbe, residencia_ancianos)
not(trabaja(abbe, _)) 
gusta(abbe, carne)
come(abbe, churrasco)
come(abbe, criollo)
come(abbe, chorizo)
not(aficcion(abbe, _))
es(abbe, jubilado)
gusta(abbe, contar_historias)

mujer(jackie_bouvier)
madre(jackie_bouvier, marge)
hijo(marge, jackie_bouvier)
adunto(jackie_bouvier)
not(vive(jackie_bouvier, ciudad))
es(jackie_bouvier, jubilada)
come(jackie_bouvier, churrasco)
not(come(jackie_bouvier, criollo))
aficcion(jackie_bouvier, _)

mujer(patty_bouvier)
hermanos(patty_bouvier, marge)
hermanos(marge, patty_bouvier)
adulto(patty_bouvier)   
vive(patty_bouvier, piso_springfield)
hermanos(selma, patty_bouvier)
hermanos(patty_bouvier, selma)
hermanos(selma, marge)
hermanos(marge, selma)
comparte_piso(patty_bouvier, selma) 
trabaja(patty_bouvier, oficina_trafico)
come(patty_bouvier, churrasco)
come(patty_bouvier, criollo)
come(patty_bouvier, chorizo)
aficcion(patty_bouvier, fumar)

adulto(selma)
comparte_piso(selma, patty_bouvier)
trabaja(selma, oficina_trafico) 
come(selma, churrasco)
come(selma, criollo)
come(selma, chorizo)
aficcion(selma, fumar)

adulto(lenny_leonard)
trabaja(lenny_leonard, central_nuclear)
hombre(lenny_leonard)
come(lenny_leonard, churrasco)
come(lenny_leonard, chorizo)
not(come(lenny_leonard, criollo))
gusta(lenny_leonard, beber_bar_moe)

adulto(carl_carlson)
trabaja(carl_carlson, central_nuclear)
hombre(carl_carlson)
not(gusta(carl_carlson, carne))
es(carl_carlson, vegetariano)
gusta(carl_carlson, beber_bar_moe)

adulto(barney_gumble)   
hombre(barney_gumble)
vive(barney_gumble, springfield)
trabaja(barney_gumble, piloto_helicoptero)
come(barney_gumble, churrasco)
come(barney_gumble, criollo)
come(barney_gumble, chorizo)
es(barney_gumble, borracho_ciudad)
gusta(barney_gumble, beber_bar_moe)

hombre(moe)
adulto(moe)
vive(moe, springfield)
trabaja(moe, bar_moe)
not(come(moe, churrasco))
come(moe, criollo)  
come(moe, chorizo)
gusta(moe, trabajar_bar_moe)
gusta(moe, pescar)

hombre(ned_flanders)
adulto(ned_flanders)
vive(ned_flanders, casa_lado_simpson)
vecino(ned_flanders, simpson)
vecino(simpson, ned_flanders)
trabaja(ned_flanders, zurdorium)
come(ned_flanders, churrasco)
not(come(ned_flanders, criollo))
not(come(ned_flanders, chorizo))   
es(ned_flanders, religioso)
gusta(ned_flanders, rezar)

niño(rod_flanders)
hijo(rod_flanders, ned_flanders)   
vive(rod_flanders, casa_lado_simpson)   
not(estudia(rod_flanders, colegio_primaria))
estudia(rod_flanders, colegio_religioso)
come(rod_flanders, churrasco)
not(come(rod_flanders, criollo))
not(come(rod_flanders, chorizo))
gusta(rod_flanders, rezar)

niño(todd_flanders)
hijo(todd_flanders, ned_flanders)  
vive(todd_flanders, casa_lado_simpson)
not(estudia(todd_flanders, colegio_primaria))
estudia(todd_flanders, colegio_religioso)
come(todd_flanders, churrasco)
not(come(todd_flanders, chorizo)
not(come(todd_flanders, criollo))
gusta(todd_flanders, rezar)
hermanos(rod_flanders, todd_flanders)
hermanos(todd_flanders, rod_flanders)

mujer(edna_krabappel)
adulto(edna_krabappel)
trabaja(edna_krabappel, colegio_primaria)   
come(edna_krabappel, churrasco)
come(edna_krabappel, criollo)
come(edna_krabappel, chorizo)
gusta(edna_krabappel, niños)
vive(edna_krabappel, springfield)

mujer(luann_van_houten)
adulto(luann_van_houten)
expareja(luann_van_houten, kirk_van_houten)
expareja(kirk_van_houten, luann_van_houten)
vive(luann_van_houten, springfield)
trabaja(luann_van_houten, oficina)
not(come(luann_van_houten, chorizo))
not(come(luann_van_houten, criollo))
gusta(luann_van_houten, lectura)

hombre(kirk_van_houten)
adulto(kirk_van_houten)
trabaja(kirk_van_houten, espanta_pajaros)
come(kirk_van_houten, churrasco)
come(kirk_van_houten, criollo)
come(kirk_van_houten, chorizo)
aficcion(kirk_van_houten, comer_palomitas_de_maiz)

hombre(clancy_wiggum)
adulto(clancy_wiggum)
vive(clancy_wiggum, springfield)
trabaja(clancy_wiggum, jefe_policia)
gusta(clancy_wiggum, comer)
come(clancy_wiggum, churrasco)
come(clancy_wiggum, criollo)
come(clancy_wiggum, chorizo)
gusta(clancy_wiggum, rosquillas)
aficcion(clancy_wiggum, comer_rosquillas)

mujer(sarah_wiggum)
adulto(sarah_wiggum)
vive(sarah_wiggum, springfield)
pareja(sarah_wiggum, clancy_wiggum)
pareja(clancy_wiggum, sarah_wiggum)
trabaja(sarah_wiggum, ama_casa)
come(sarah_wiggum, churrasco)
come(sarah_wiggum, criollo)
come(sarah_wiggum, chorizo)
aficcion(sarah_wiggum, leer)

niño(ralph_wiggum)  
hijo(ralph_wiggum, clancy_wiggum)
hijo(ralph_wiggum, sarah_wiggum)
vive(ralph_wiggum, springfield)
estudia(ralph_wiggum, colegio_primaria)
not(come(ralph_wiggum, churrasco)
not(come(ralph_wiggum, criollo))
not(come(ralph_wiggum, chorizo))
es(ralph_wiggum, vegetariano)
gusta(ralph_wiggum, quemar_cosas)



% Reglas
