(padre Abe Homer)
(padre Abe Hebert)
(padre Abe Abbie)
(padre Mona Homer)
(padre Mona Hebert)
(padre Mona Abbie)
(padre Homer Bart)
(padre Homer Lisa)
(padre Homer Maggie)
(padre Bart Picard)
(padre Bart Kirk)
(padre Lisa Zia)
(hombre Abe)
(hombre Homer)
(hombre Hebert)
(hombre Bart)
(hombre Picard)
(hombre Kirk)
(mujer Mona)
(mujer Abbie)
(mujer Lisa)
(mujer Maggie)
(mujer Zia)